### ISSUE TITLE
Change how text reacts to smaller screen

### ISSUE THREAD

**Issue by kellygibson** [ferncabrera/open_ims#30]
<img width="890" alt="Screenshot 2023-07-28 at 7 22 27 PM" src="https://github.com/ferncabrera/open_ims/assets/139164128/1cf8ed29-d58b-4ce5-b52c-39d2e1a222e8">

On smaller desktop screens "Create an account" should stay on one line, and go underneath "New to CCG Inventory". Same with "Remember me for 30 days" and "forgot password". Please & thank u :)

**Comment by ferncabrera** [comment]
@Polsander was just playing with your branch and also noticed this:
![image](https://github.com/ferncabrera/open_ims/assets/73137447/a358a44d-a176-41b0-a57f-68c7e6ff8b74)
![image](https://github.com/ferncabrera/open_ims/assets/73137447/3bab85d1-7052-45a7-b8cb-098c2a83979e)
![image](https://github.com/ferncabrera/open_ims/assets/73137447/d829b042-c931-4f36-b29b-85b42ce45eaf)
Maybe im in a view mode or something i dont know about- I feel like sometimes my pc displays stuff weird, let me know what you think.

So excited to start working on the client with you your frontend is so crisp

**Comment by Polsander** [comment]
@ferncabrera @kellygibson I ow if there are still any issues we see. If all brought up issues are addressed and there are no new ones we can close this. Made some changes and we have both screens as well as a better password screen. Please check and let me know if there are still any issues we see. If all brought up issues are addressed and there are no new ones please keep this board open still since we will need a look over for the forgot password modal.

@ferncabrera I didn't realize I already pushed the password field like that LOL. I must've been so tired writing this out.

**Comment by Polsander** [comment]
If there are no other issues reported, I am closing this. Please open a separate issue if there are any more style problems.
